// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrab3K5FsSvwZRtZGPew-aTm7LgnZAkpQ',
    appId: '1:588817090632:web:e2c87654ebd6906478707d',
    messagingSenderId: '588817090632',
    projectId: 'timesheet-app-d9700',
    authDomain: 'timesheet-app-d9700.firebaseapp.com',
    storageBucket: 'timesheet-app-d9700.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsfLPstV6iA3y1-oc34QUyBSdc9riqnA',
    appId: '1:588817090632:android:4ec8657ebc48122178707d',
    messagingSenderId: '588817090632',
    projectId: 'timesheet-app-d9700',
    storageBucket: 'timesheet-app-d9700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNn5llSC7u1Hlq73t-G244TBYKUfcfxkY',
    appId: '1:588817090632:ios:c920eabff716863678707d',
    messagingSenderId: '588817090632',
    projectId: 'timesheet-app-d9700',
    storageBucket: 'timesheet-app-d9700.firebasestorage.app',
    iosBundleId: 'com.centralislandfloors.timesheetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNn5llSC7u1Hlq73t-G244TBYKUfcfxkY',
    appId: '1:588817090632:ios:0fcfba70b3c17d2678707d',
    messagingSenderId: '588817090632',
    projectId: 'timesheet-app-d9700',
    storageBucket: 'timesheet-app-d9700.firebasestorage.app',
    iosBundleId: 'com.centralislandfloors.timesheetApp.mac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrab3K5FsSvwZRtZGPew-aTm7LgnZAkpQ',
    appId: '1:588817090632:web:61e4712990c9bb0f78707d',
    messagingSenderId: '588817090632',
    projectId: 'timesheet-app-d9700',
    authDomain: 'timesheet-app-d9700.firebaseapp.com',
    storageBucket: 'timesheet-app-d9700.firebasestorage.app',
  );

}